name: test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
        image: osmtw/rudymap:latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: foo
        run: pwd
